= Paperless Trade White Paper
:title: Paperless Trade White Paper
:subtitle: How Does It Impact the Trade System
:doctype: plenary
:docnumber: GE.18-02016(E
:committee: United Nations Centre for Trade Facilitation and Electronic Business (UN/CEFACT)
:copyright-year: 2018
:session: 24
:session-date: Geneva, 30 April – 1 May 2018
:agenda-item: Item 6 of the provisional agenda 
:collaborator: World Economic Forum
:agenda-id: ECE/TRADE/C/CEFACT/2018/6
:docnumber:    GE.18-02016(E)
:revdate:  9 February 2018
:language: English
:distribution: General

[abstract]
In 2017, the World Economic Forum approached UN/CEFACT in order to create a guide on Paperless Trade which might help countries to understand and implement specific provisions of the World Trade Organization’s Trade Facilitation Agreement, specifically article 10 on Formalities connected with importation and exportation (10.2, 10.3 and 10.4) as well as article 7 on Release and clearance of goods (7.1 and 7.2).

This White Paper provides a brief history on standardization of electronic business processes, especially within UN/CEFACT; the basics, benefits and challenges in electronic business processes; the governance of paperless trade; and future evolutions.

This document has been published by the World Economic Forum in October 2017 under the reference 261017, case 00036073.

This document is submitted to the twenty-fourth UN/CEFACT Plenary for noting.


== Introduction: What is Paperless Trading?
When goods and services cross borders in international trade, information needs to be passed between relevant parties, whether private companies or public bodies, including suppliers, logistics providers, customs, regulatory agencies, sellers and buyers. Paperless trade refers to the digitization of these information flows, including making available and enabling the exchange of trade-related data and documents electronically. Less formally, one can think of this as cross-border trade transactions using electronic data in lieu of paper-based documents.

Transforming what was traditionally a paper-based documentation system into an electronic format can speed up trade and ease the cost of doing business in today’s interconnected world. Bottlenecks in supply chain management and regulatory documentation can be particularly tricky for smaller businesses or e-traders with less experience and resources. Paperless trading, therefore, serves as a promising means to deal with the logistical challenges of e-commerce and, in particular, small shipments across borders. Overall, it is quickly becoming an essential component of governmental efforts to improve the efficiency of customs controls and trade administration processes, and of ensuring trade competitiveness in a rapidly digitizing world.

How exactly is a trade transaction rendered paperless? Digitized exchange can be done in several ways. One way is simply to take a visual snapshot of a paper document – either a scanned or a PDF version. Another possibility is an internet web portal where individual data elements can be keyed in – this is known as data-trader interface (DTI). Paperless transactions can also be conducted using fully electronic messages – known as electronic data interchange (EDI), with formats including UN/EDIFACT, XML, JSON and other web services. Typically, these systems would provide an application-programming interface (API) to facilitate interaction with the database.

At first glance, the task of moving from paper-based to paperless administration of trade may seem relatively straightforward. However, because of the need to coordinate electronically across borders, the impetus for international cooperation rises once trade is rendered paperless. Governments use a variety of arrangements, including United Nations (UN) agencies and standards-setting organizations, as well as trade agreements, to establish the governance structures necessary for paperless trading. This white paper provides an overview of these efforts, which take place across a wide variety of disparate institutions, some of which lie outside the traditional institutions associated with trade governance.

The paper is written especially with trade policy-makers in mind to assist their considerations on how best to align trade rules with current and expected future trends in paperless trading. The paper is also intended to provide other stakeholders with a better understanding of existing efforts and possible future developments at the intersection of paperless trading and international trade administration to guide their inputs for trade policy.

Because of the wide variety of issues associated with paperless trading, it is important to establish boundaries in the scope of what is considered in this paper. Though scanned/PDF files can present benefits, this white paper concentrates primarily on transactions conducted through electronic messages. Electronic messages afford even greater opportunities for tapping into the benefits of paperless trading thanks to the potential reuse of data, the elimination of the need to re-key data into a computer at each supply chain checkpoint, and the reduction in potential human error. Note that aspects of this paper may apply to DTI and APIs as well.

The paper is also specifically focused on paperless trade as defined by the technical international trade community. This encompasses electronic forms of trade administration documents that are business-to-government (B2G) as well as business-to-business (B2B) electronic exchange of information within international trade context. The term “paperless trade”, however, can be used by other communities in a broader sense to refer to the electronic exchange of data in a purely national commercial and regulatory context. For example, banks may refer to paperless trade as applied to trade finance processes – which may also have an international component. Further, different stakeholders may diverge on where the line may be drawn on what is considered paperless trade as applied to trade administration documents versus the broader digital commercial universe. The potential for different starting points on paperless trade should be kept in mind when engaging in dialogue on the topic.

The paper is a part of a series run by the World Economic Forum and the World Trade Organization (WTO) focused on e-commerce policy best practices. The inclusion of paperless trade in the series is from both the perspective of the digitalization of trade processes as well as the specific benefits this may have for small businesses using electronic platforms to engage in global trade.

== How Does Paperless Trading Work?
While many may be familiar with the concept of paperless trading, the mechanics of how exactly paperless trading works is one that most individuals involved with trade, whether from business or government, will have given little thought. Like many other elements of our digital world, it is simply a technical development that is taken for granted. However, a basic overview of how it works in practice and the benefits may help inform debate on the need for cross-border cooperation on technical issues.

For parties to exchange and reuse fully electronic messages, all information needs to be clearly defined and unambiguous, both from a semantic and syntactical perspective. Trading partners wanting to exchange data will need to agree on the meaning of each individual data element to ensure that they all understand the information in the same way. This is equally true for governments and any other parties that may use or transmit this data. If the exchange is limited to two parties, a bilateral data dictionary is sufficient. As soon as there are multiple parties, however, or if the information may be reused in other contexts, a standardized data dictionary is useful.

When a commercial order is received, a system configured to use EDI messages can prepare all the necessary documents (or messages) to enable processing – such as packing list, delivery note, invoice and customs declaration. The system can also potentially manage reorders for stock replenishment and link to other entities to order transport, request certificates or arrange other services.

Code lists are another important part of moving from paper to electronic messages. Any information that can be codified should be codified to avoid confusion. For example, in English alone, packaging material that is palletized can be described as slab, board, honeycomb slate and so on, before even taking into account differences between languages. Humans might understand that each of these means palletized or stacked on pallet transport structures, but a computer, unless it has been programmed to recognize all the variations, will not necessarily understand that these are the synonymous terms. However, if “palletized” is indicated using a code, there is no ambiguity.

The technical challenges of facilitating paperless trade have been addressed by governments and supply chain actors in various forums and formats. UN agencies have played a key role in developing international standards for the electronic representation of information required for trade documentation – helping to boost connectivity and interoperability. The United Nations Economic Commission for Europe (UNECE) founded the Working Party on Facilitation of International Trade (WP.4) as early as 1961 to “facilitate international trade and transport by promoting rationalization of trade procedures and the effective use for this purpose of electronic or other automatic data processing and transmission.”footnote:[Terms of Reference of the Facilitation of International Trade Procedures: http://www.unece.org/trade/facil/wp4_tor.htm (link as of 09/2017)]

=== Benefits for Traders

Over the past two decades, global trade has been increasingly defined by complex international production networks. Modern commerce is no longer an exchange between two parties but rather an extended collaboration between critical interdependent partners executed over vast geographic expanses, time zones and borders. The degree to which partners in a B2B context are proficient and make use of the network defines their success, hinged on the ability to process information using the internet and messaging protocols. The rise and spread of the internet, and with it the ability to send electronic files, radically transformed business information-sharing models – often allowing a number of authorized trading partners to stay updated simultaneously thereby keeping the entire network in sync. Paperless trade systems streamline the flow of information in global supply chains by simplifying the exchange of necessary documents or contractual elements – whether B2B or B2G – that accompany inputs crossing borders multiple times.

As such, paperless systems can generate savings for traders through faster movement of goods as well as greater efficiency at border agencies where the exchange involves trade administration documents. Data exchanged includes purchasing orders, inventory reports, and digital sanitary and phytosanitary (SPS) certificates, among others. Paperless trade can also help businesses meet regulatory compliance obligations more efficiently and at a lower cost – whether the concept is applied in a domestic or international context.

In some countries operating manual systems, official processes are also accompanied by steps added over time, resulting in systems littered with exceptions and complexity – for example, differing from point of entry to another. Dematerializing trade administration processes can help to create a system that is more difficult to modify informally.

Reductions in trade costs and efficiency via paperless trade can be particularly helpful for small and medium-sized enterprises (SMEs) using e-commerce platforms to access international markets.footnote:[http://artnet.unescap.org/pub/WP146.pdf (link as of 09/2017)] E-traders may have more limited resources to manage additional trade documentation, or doing so for relatively low value parcels may be uneconomical. For example, one survey found that where EDI files were not accepted in some countries, each parcel needed to be declared individually (contents, dimensions and weight).footnote:[https://www.wto.org/english/tratop_e/serv_e/wkshop_june13_e/ecom_national_board_e.pdf (link as of 09/2017)] Delivery delays due to waiting times at the border can be damaging for e-traders relying on good customer reviews to build trust.footnote:[https://www.intracen.org/uploadedFiles/intracenorg/Content/Publications/Bringing%20SMEs%20onto%20the%20e-Commerce%20Highway_final_250516_Low-res.pdf]

As electronic messages typically move much faster than physical merchandise, implementing paperless trade systems has also driven major innovations in international supply chains, such as “just-in-time” delivery. Using this approach, companies can hold as little stock as possible, ordering merchandise when it needs to be sold or used. Modern supply chains must equally adapt to ever-shortening production lifecycles, consumer tastes and rapid technological developments. Without electronic messages in the supply chain, these developments would be difficult.

Further, paperless trade systems have facilitated the emergence of “third-party logistics” (3PL) players that offer elements of distribution and fulfilment for clients. These play a vital role in the planning and execution of global trade. Some commercial solutions – such as customs APIs – offered by several logistics services providers can particularly help e-traders navigate customs clearance by enabling the integration of shipping and regulatory processes into their business systems and websites. Some logistics providers also offer landed cost calculators for e-traders to display the full cost of the product – including customs duties, shipping and transport – upfront to potential buyers and mitigate potential conflicts.footnote:[https://www.clarity-ventures.com/ecommerce/-all-features/cutting-edge-logistics-integrations/customs-and-duties-integration (link as of 09/2017)] More broadly, the operational side of trade today hinges on the inclusion of third-party specialists covering freight forwarders, quality-assurance teams, customs brokers and transport carriers for ocean, air and road – many of which deploy dematerialized processes in a B2B context.

=== Benefits for Governments

By enabling real-time information on the location and status of a shipment, paperless trade can improve transparency and traceability. As supply chains become more complex, traceability has been sought by consumers, business and governments across all manner of products, to ensure labour, environmental and other standards. While traceability can be achieved through paper-based systems, digital systems are timelier and can reduce fraud. On the latter, paperless trade can help to tackle illegal and counterfeit trade or trade-based money-laundering by increasing the visibility on exported goods and easily exposing trades that make no commercial sense. Paperless trade can also help governments more efficiently to address growing security concerns and the need to ensure there are no potential threats hidden in commercial packages. Electronic data exchange, where two governments have agreed to do so, can enable a better tracking of the value of goods declared – in some manual systems, exporters might over-declare to maximize tax recovery, while an importer might under-declare to pay less import duties. Recent evolutions in technology, such as blockchain, could provide benefits in ensuring the integrity of data.

Paperless trade can also play a key role in cross-border regulatory cooperation. For example, standardized electronic data messaging language maintained by UN agencies can enable countries to exchange electronic SPS certificates for agriculture products or communicate laboratory results in the agri-food industry. The International Plan Protection Convention (IPPC) multilateral treaty under the UN Food and Agriculture Organization (FAO) is developing a globally harmonized approach for electronic phytosanitary certificates exchange – used to check the quality of food products – that will use UN e- business standards.footnote:[As developed by the United Nations Centre for Trade Facilitation and e-Business (UN/CEFACT). See more here: https://www.ippc.int/en/ephyto/ (link as of 09/2017)] Another UN standard on electronic exchange of fishery data – including fishing locations, species and quantity caught and so on – could improve sustainable fisheries management and trade.footnote:[UN/CEFACT’s Fisheries Language Universal Exchange (FLUX) standard enables record and exchange of harmonized electronic data from fishing vessels to other parties. This could be one tool in help fisheries management traceability efforts in the supply chain in order to help reduce the incidence of illegal fishing and trade. https://www.unece.org/info/media/news/trade/2017/unece-showcases-its-contribution-to- halt-overfishing-at-un-ocean-conference-in-new-york/doc.html (link as of 09/2017)]


Many countries are developing single windows that serve as one simple point of entry for submitting regulatory documents and other supporting evidence when merchandise is imported or exported. Almost all single windows implemented today are electronic systems with a web-based interface. As such, running an electronic single window usually requires the ability to process electronic message exchanges. The World Trade Organization (WTO) Trade Facilitation Agreement (Article 10.4) includes an endeavour to maintain or establish a single window using information technology to the extent possible and practicable. According to the United Nations Economic Commission for Europe (UNECE) Recommendation 33,footnote:[The first international description and recommendation on Single Window, “Recommendation and Guidelines on establishing a Single Window to enhance the efficient exchange of information between trade and government Recommendation 33” UNECE 2005, see page 3, point 2: http://www.unece.org/fileadmin/DAM/cefact/recommendations/rec33/rec33_trd352e.pdf (link as of 09/2017)] a single window is a facility that allows parties involved in trade and transport to lodge standardized information and documents with a single entry point to fulfil all import, export and transit-related regulatory requirements. If information is electronic, individual data elements should only be submitted once.

Implementing paperless trade and electronic single-window systems can contribute to improving a country’s international commercial-enabling environment, encouraging more business activity, in turn driving economic growth and development. In Senegal, for instance, the implementation of the electronic single window reduced the border pre- clearance and clearance processing time by 90%, from an average of two weeks to just one day. The cost of border processes has decreased by 60%, while the streamlined system has allowed the border agencies to reassign staff to other priority areas.footnote:[African Alliance for E-Commerce and World Bank. AACE Single Window Peer Review: Senegal. 2014.] In Costa Rica, the Inter-American Development Bank finds that the implementation of the electronic single window increased exports by 2% a year from 2007-2013. Looking at the cost-benefit analysis, an approximate $1.7 million invested in the system translated into a twentyfold gain in terms of increased exports and reductions in public administration costs.footnote:[Volpe Martincus, Christian. _Out of the border labyrinth: an assessment of trade facilitation initiatives in Latin America and the Caribbean._ Inter-American Development Bank. 2016. P. 200
] This is equal to a rate of return of roughly $16 for every dollar paid. Peru also established a Single Window for Foreign Trade in 2010, which improves coordination by connecting eight government institutions that issue export and import permits, as well as shipping-related entities.footnote:[http://www.intracen.org/publication/SME-Competitiveness-Outlook-Meeting-the-Standard-for-Trade/ (link as of 09/2017)]

== Paperless Trade Challenges
Paperless trade is not without challenges. The set-up and operation of paperless trade measures, supporting regulation and electronic single windows, is not yet a given across all countries. The UN has conducted a survey of 120 countries, across a range of 38 measures related to trade facilitation and paperless trading. From a subset of factors relevant to all survey countries, it was then able to derive an average implementation score; a score of 100% reflects full implementation across all factors. The average implementation rate of trade facilitation and paperless trade measures from the most recent 2017 survey 61%.footnote:[http://www.unescap.org/news/good-progress-made-implementing-wto-trade-facilitation-agreement-still-long-road-paperless-and (link as of 09/2017)] This figure reflects steady improvement over the past two years but also highlights the degree to which most countries have yet to implement the full range of possible measures.footnote:[Note that the average implementation rate in 2015 was 53%. See https://unnext.unescap.org/content/global-survey-trade-facilitation-and-paperless-trade-implementation-2015 (link as of 09/2017).]

Even more alarming is the fact that only about 34% of countries have implemented measures related to the cross-border exchange of electronic data and documents.footnote:[See supra note 11.] Results from the OECD-WTO Sixth Global Aid for Trade Review show that while most IT border systems in developed and emerging economies can be used for EDI-based exchange, this is still under implementation in many low-income economies. Countries with less clear legislation, weaker infrastructure and lower IT capacity can face hurdles in implementing paperless systems.

Furthermore, only about 40% of all upper-middle income countries have single windows in place, while the figure is 20% for lower-middle income countries and less than 10% in low-income countries.footnote:[https://www.wto.org/english/res_e/booksp_e/aid4trade17_e.pdf] The OECD finds that progress on implementing single windows is often linked to the quality of cooperation and information exchange among various government agencies, customs departments and border control posts.footnote:[Ibid.] Single-window implementation may pose a bigger challenge for countries more reliant on imports due to complexity. Some systems may also not satisfy the five-point definition of a “single window” – whether because there is not a governmental mandate resulting in multiple systems or there is not a clear single entry point. Where single windows do not distribute information to all relevant regulatory bodies, traders may still need to submit information several times.

Paperless trading is also reliant on domestic rules on the legal validity of electronic documents, electronic signatures, where these are applied, and other data-regulation requirements. Further, if paperless trade is to be effective in the international trade- enabling context, governments must accept data at customs and within regulatory agencies without also requiring original paper documentation. In other words, a paperless system that still requires the submission of paper-based documents at some point in the trading chain destroys much of the value of the digital tools for traders.

Finally, capacity building may be needed to boost paperless trade use. SMEs and e-traders may lack access to the internet, encounter slow connections, or pay high usage rates. Even with access, they may not have the digital skills to use new IT systems or services or be able to maximize the advantage of going paperless.footnote:[http://www.intracen.org/publication/Bringing-SMEs-onto-the-e-Commerce-Highway/ (link as of 09/2017)]

== Technical Standards for Paperless Trading: A brief history
As is true of any system with complex technical arrangements that require cross- border cooperation, international standards have emerged for different facets of paperless trade. This section provides a quick overview of these standards, including their historical evolution.

[IMPORTANT]
.The United Nations Centre for Trade Facilitation and e-Business
====
The United Nations Centre for Trade Facilitation and e-Business (UN/CEFACT) is an intergovernmental body of the UNECE. It develops policy recommendations and standards based on public and private sector collaboration. Work on these deliverables requires the support of at least three UN Members. Completed projects are presented to the UN/CEFACT Plenary – which any UN Member can join – for approval. In this way, all countries can participate in the standardization process. All results are available free of charge.

UN/CEFACT aims to be a semantic hub for data elements. It maintains a Core Component Library (CCL) that serves as an encyclopedia of data elements and includes inputs from other organizations with electronic business standards; this is outlined in a multilateral MoU between UNECE and the International Standards Organization (ISO), International Telecommunications Union (ITU) and International Electrotechnical Commission (IEC). A long-term objective is to harmonize various data elements and render the base semantics compatible between different standards bodies. Other bodies such as the World Customs Organization (WCO) have aligned their data requirements with past CCL libraries as demonstrated in a case study in <<annex-b>>.
====

International technical standards play an important role in trade governance, in large part due to the WTO Agreement on Technical Barriers in Trade (TBT Agreement) and similar language in free trade agreements (FTAs)/regional trade agreements (RTAs). WTO Members are required to base their technical regulations for trade in goods on international standards or to explain why deviation is necessary. Awareness of the existing international standards, and the institutions through which these standards are established, is important for trade policy-making. This is especially the case if paperless trading systems at the border will be integrated with domestic regulatory systems concerning the distribution and sale of goods behind the border.

Disparate institutions at the multilateral and regional levels are involved in the creation of these international technical standards. Because of the division of responsibilities within government bureaucracies, some trade policy-makers will not necessarily be aware of the work of other officials within their own government in establishing these technical standards, despite the fact that the creation of such standards will inevitably impact traders. The discussion below is also intended to flag for trade policy-makers the various forums through which international technical standards governing paperless trading are being shaped, so that they can better coordinate their policy-making objectives on paperless trade within their government.

Efforts to improve cross-border exchange of trade information date back more than 50 years. The UN Layout Key was developed in the 1960s to standardize the representation of information on trade documents. It was quickly accompanied by a data dictionary so all parties would consistently understand the same thing. The birth of the UN Trade Data Element Directory, or UN/TDED, was the first essential step towards electronic messages.

As mentioned above, code lists are another important feature of paperless trade, allowing for better mutual understanding of content as textual information may be incomplete, misleading or uninterpretable. UN/CEFACT maintains a number of code lists that can be downloaded free of charge and are often used by other standard-setting bodies to increase interoperability. Further information on UN/CEFACT code lists is included in <<annex-a>>.

The availability of a data dictionary and the use of code lists combined with an exponential growth in the use of computers led to the creation of standardized messages for data exchange. The UN Electronic Data Interchange for Administration, Commerce and Transport (UN/EDIFACT) was one pioneer in this area – effectively replacing some paper documents from the mid-1980s onwards. Similar initiatives took place regionally.

UN/EDIFACT is a syntax or message exchange language that is centrally maintained by UN/CEFACT. Some messages are developed by other organizations and then submitted to UN/CEFACT to be harmonized and entered into the official directories. The messages are identified by a six-character name, such as INVOIC for invoice or CUSDEC for a customs declaration, and the information is organized into groupings, similar to those found on paper documents including importer information, product details, payment conditions, and so on. Each grouping has a strict format – such as length and type of information – much of which was inherited from paper documents. Further information on the technical functioning of UN/EDIFACT messages is detailed in <<annex-a>>.

UN/EDIFACT was the dominant messaging syntax throughout the 1990s and remains likely the most widely used single standard for data exchange – especially since it is freely available and is regularly updated. While official statistics are hard to come by, sectoral estimates, such as those by the maritime industry, indicate that about 8,000 EDIFACT messages are exchanged per day.

Even so, over the past two decades an increasing number of exchanges use XML. This EDI syntax provides higher flexibility in the structure, length and format, often making it more attractive. However, there is no single, centrally maintained XML version – there could potentially be as many XML languages as business partners. Other technical disadvantages include larger data files. UN/CEFACT does offer a standardized XML, as do some International Organization of Standards (ISO) committees, the World Customs Organization (WCO), the International Air Transport Association (IATA) and others. The UN/CEFACT approach to XML has been to start standardizing the processes and then the data related to each process is to contain before creating XML messages. Further information on XML languages is contained in <<annex-a>>.

The use of electronic invoices merits particular attention. The European Union has decided that all public institutions must accept and may require electronic invoices, as part of a wider drive to decrease the use of paper. Two standards should be used to ensure interoperability, one of which is the UN/CEFACT Cross Industry Invoice (CII). All public institutions – from elementary schools to garbage collection, from town halls to ministries – will be obliged to accept the CII as one of the official standards for the submission of electronic invoices.footnote:[See case study in <<annex-b>>] Other countries are also seriously studying implementation of the CII.

The CII is accompanied by a series of messages, beginning with the term cross- industry, which aim to cover a range of domain needs from agriculture to automotive and industrial services. Cross-industry messages cover invoice, ordering, catalogue, quotation, delivery, remittance and so on. These have today been consolidated into a Supply Chain Reference Data Model that enables a process-driven approach instead of a document- driven approach to supply chain information exchanges.

== Key Principles for Paperless Trading

From all of the above, it is hardly surprising that paperless trade is often seen as a tech-driven process. But this is only partially true; implementation requires, first and foremost, a high-level political consensus, policy frameworks, supporting laws and legislation and an institutional set-up. A policy framework may define targets and implementing strategies and detail the necessary allocation of resources, while enabling legal structures includes laws and statutes, implementing decrees and regulations and contractual provisions – such as for the terms of use or the provision of electronic single windows or e-Port Community Systems.

Efforts towards uniform supporting legislation came a decade after the initiation of technical standards for paperless trade, largely through the United Nations Commission for International Trade Law (UNCITRAL), which developed model laws relevant to electronic transactions, e-commerce and e-signatures.footnote:[For further information on electronic transactions and e-signatures, see “Making Deals in Cyberspace: What’s the Problem,” World Economic Forum, October 2017.] These model laws include several key governance principles.

The first is the principle of non-discrimination between the use of electronic communications and paper when submitting documents such as those required by regulatory agencies. Laws that allow the submission of electronic information are essential for launching an effective paperless trade system.

Second, the principle of functional equivalence implies that paper-based functions may be replicated by electronic communications or procedures, which may or may not be mirror images of paper-based procedures but fulfil the same legal functions.

Third, applying the principle of technological neutrality implies ensuring that legislation does not favour specific technologies. In a rapidly changing digital and technology environment, paperless trade policy frameworks must be open to future developments. Detailed provisions on technical requirements can be contained in implementing regulations that are easier to adapt as needed.

These principles have been carried forward in some trade and regional integration contexts. Part of the legal framework for electronic contracting is also based on standard contracts and rules such as the Incoterms and the Uniform Customs and Practice for Documentary Credits of the International Chamber of Commerce.footnote:[UN/CEFACT provides a code list for Incoterms in Recommendation No. 5.] Paperless trade policy frameworks can also relate to issues on data authentication and security as well as data protection and retention, including data archiving and sharing.

== Global Governance of Paperless Trade
At present, a number of efforts exist to advance interoperable paperless trade policy frameworks through a variety of approaches. These include recommendations from UN agencies, trade deals and regional integration initiatives. Importantly, these ongoing efforts exist across institutions and are not necessarily coordinated.

One approach has been to focus on shaping non-obligatory norms, or suggested recommendations, for governments to follow. UN/CEFACT plays a key role in developing trade facilitation recommendations targeting high-level policy-makers that typically touch on specific aspects of paperless trade. For example, Recommendation 12 applies to facilitating maritime transport documentation through a principle of an electronic sea waybill to replace the paper-based bill of lading. Recommendation 14 provides guidance on electronic authentication for trade documents.

Another approach has been to develop treaty provisions. The WTO TFA, a multilateral deal that entered into force in February 2017, contains a number of provisions potentially relevant to paperless trade. These refer to the electronic exchange of data and documents, the electronic submission of trade related documents, e-payment systems, electronic single window systems and international standards for paperless trade. Some specific references are detailed in <<table1>> (below), although others could also be considered.

While covering aspects related to paperless trade, the textual language of the TFA leaves much room for WTO Members to shape their own systems and legal frameworks. The TFA is also crafted to take into account individual country situations and capacities. To benefit from the special and differential treatment provisions found in the agreement, WTO Members must categorize and notify their ability to fulfil each provision and may signal the need for support for implementation. Estimates suggest that full implementation of the TFA – which includes but goes beyond paperless trade administration provisions – could reduce trade costs by an average of 14.3% and boost global trade by up to $1 trillion a year.footnote:[https://www.wto.org/english/res_e/booksp_e/world_trade_report15_e.pdf (link as of 09/2017)]

[[table1]]
.WTO TFA provisions relevant to paperless trade
|===
|Article |Provision

|Article 7.1 |  “Each Member shall, as appropriate, provide for advance lodging of documents in electronic format for pre-arrival processing of such documents.”
|Article 7.2 | “Each Member shall, to the extent practicable, adopt or maintain procedures allowing the option of electronic payment for duties, taxes, fees, and charges collected by customs incurred upon importation and exportation.”
|Article 10.2 | "Each Member shall, where appropriate, endeavour to accept paper or electronic copies of supporting documents required for import, export, or transit.”
|Article 10.3 | Encourages Members to “use relevant international standards or parts thereof as a basis for their import, export, or transit formalities and procedures” which in theory would apply to standards relevant for e- commerce as well.
|Article 10.4 |  “Members shall endeavor to establish or maintain a single window, enabling traders to submit documentation and/or data requirements for importation, exportation, or transit of goods through a single entry point to the participating authorities or agencies.” The article further stipulates that “Members shall, to the extent possible and practicable, use information technology to support the single window.”
|===

Besides these texts, paperless trade provisions commonly feature in FTAs. Indeed, the first e-commerce provision found in any trade deal addresses paperless trade, specifying that parties should have in place an electronic environment supporting electronic business application between their customs administrations and trading community.footnote:[2001 RTA between New Zealand and Singapore, as referenced in https://www.wto.org/english/res_e/reser_e/ersd201711_e.pdf (link as of 09/2017)] One study found that more than half of the trade agreements in play since 2005 address paperless trade in some shape or form.footnote:[Duval, Yann and Kong Mengjing. Digital Trade Facilitation: Paperless Trade in Regional Trade Agreements. ADBI Working Paper Series, June 2017. Available at https://www.adb.org/sites/default/files/publication/321851/adbi-wp747.pdf (link as of 09/2017) Note that this study uses a broader definition of paperless trading than the WTO study referenced below.] Specifically, in a recent study of regional trade agreements, the WTO notes that paperless trade administration provisions are found in the e-commerce chapter of 47 RTAs (or 32 RTAs if provisions referring to e- government are excluded) and in the customs procedures or trade facilitation chapters of 39 RTAs. In addition, related provisions on electronic procurement can be found in the government procurement chapter of 25 RTAs. Overall, paperless trade provisions are the sixth most common type found in RTA e-commerce chapters.footnote:[ https://www.wto.org/english/res_e/reser_e/ersd201711_e.pdf (link as of 09/2017)]

The focus area and coverage of these provisions, however, can vary greatly. Specific articles on paperless trading often take the form of soft, rather than hard binding commitments where negotiators use language such as “shall endeavour”. The provision is usually accompanied by a definition of trade administration documents.footnote:[WTO research notes that this typically refers to forms issued or controlled by the government of a party, which must be completed by or for an importer or exporter in relation to the import of export of goods. The FTA between Japan and Switzerland is the only agreement notified to the WTO that extends the definition to forms that a party issues or controls that must be completed by a services supplier. For more, see: https://www.wto.org/english/res_e/reser_e/ersd201711_e.pdf (link as of 09/2017)] Paperless trading provisions frequently require that a government make publicly available electronic versions of all trade administration documents – sometimes specifying a time-delineated implementation goal. These also typically require the government to accept trade administration documents submitted electronically as the legal equivalent of the paper version of such document.

Select FTAs require parties to work towards the implementation of initiatives that support paperless trading – such as electronic single windows. An FTA between Chile and Australia, for example, refers to the development of a single window with cross- referencing between the e-commerce and customs chapters. Several FTAs see parties pledge to use international standards or methods when developing paperless trade systems, which can be a good way to ensure interoperability.

Some countries have inserted provisions on cooperation in relation to paperless trading. This can take the form of sharing experiences on regulations, laws and programmes on e-commerce and e-government – with the latter a proxy for paperless trading – or regulatory dialogue. A limited number of agreements require parties to cooperate bilaterally and in international forums to enhance the acceptance of electronic versions of trade administration documents. The Japan-Singapore FTA commits parties to encourage cooperation between relevant private entities engaged in paperless trading and establishes a joint committee on paperless trade geared towards reviewing implementation issues.

The minority of FTAs in which the language of the standalone “paperless trading” provision is drafted as a binding obligation almost all concern an FTA with Australia or New Zealand. These include the Australia-China FTA, Australia-Malaysia FTA, Australia- Singapore FTA, Australia-Thailand FTA and New Zealand-Thailand FTA. Each of these agreements allows limited exceptions if there is a “domestic or international legal requirement to the contrary” or if paperless trading would “reduce the effectiveness of the trade administration process”.
 
Among recent FTAs, the Trans-Pacific Partnership (TPP) had the broadest comprehensive coverage in terms of elements related to paperless trading. It included acceptance of electronic copies; e-submission of trade-related documents such as SPS certification; electronic customs systems; e-certification and e-signature, including mutual recognition; and international standards. Besides the TPP, other FTAs with a broad scope of coverage include the US-Republic of Korea FTA and several other recent Korean FTAs (such as those with China and Viet Nam).

In general, the breadth of paperless trading elements is broadest for FTAs negotiated in the Asia-Pacific, reflecting the region’s leadership in this area. While the EU has focused on building paperless trading systems for its members, FTAs negotiated by the European Commission tend not to put as much emphasis on paperless trading as compared to those negotiated by the US, Australia, Republic of Korea, or others. The EU agreement with Colombia and Peru includes the commitment to endeavour to make trade management documents available electronically and to accept electronic documents as the legal equivalent of paper. The agreement with Korea includes cooperation on implementing paperless trading.

The UN Economic and Social Commission for the Asia-Pacific (UNESCAP) adopted a Framework Agreement on Facilitation of Cross-Border Paperless Trade in May 2016 to advance regional coherence. The treaty is designed to provide new tools and a digital complement for implementing the TFA and facilitating cross-border commerce. Among other things, it will help to promote general principles to enable the exchange and mutual recognition of trade-related data and documents in electronic form. Some estimates suggest full implementation could boost Asia-Pacific exports by as much as $257 billion annually, while the time taken to export could fall by 44%. Cost savings across all trade in the Asia-Pacific region could be worth $7 billion annually.footnote:[“New UN treaty to facilitate paperless trade in Asia and the Pacific to support Trade Facilitation Agreement implementation.” Trade Facilitation Agreement Facility, 1 October 2016. Available at http://www.tfafacility.org/new-un-treaty-facilitate-paperless-trade-asia-and-pacific-support-trade- facilitation-agreement (link as of 09/2017)] The UNESCAP Framework Agreement includes specific provisions to consider requests from least developed and landlocked developing countries for technical assistance to develop paperless trade capacities.

== Technical Considerations Looking Ahead
On the one hand, the constant evolution of technology requires avoiding regulation that locks in one particular solution. On the other hand, the introduction of new technologies or standards into trade processes will create disruptions for actors in the supply chain, so transition plans will be essential.

To date, it is worth noting that electronic messages have been treated as a direct alternative to paper documents, with paperless trade effectively taking a “document-driven” approach with the information in electronic messages being organized in line with corresponding documents, such as invoice, bill of lading, customs declaration and so on. However, this does not optimize the information being gathered. Most documents are part of a chain of information exchanges and a good deal of information tends to be repeated at each step whether on the paper document or an electronic equivalent.

A process-driven approach to the chain of information exchanges would instead consider each exchange within the context of other exchanges related to the same process. Each electronic message in the chain only needs to contain new information, rather than repeating redundant information. The approach implies rethinking how information is exchanged. It also corresponds more closely to the one-time data entry called for in single windows, as defined in UNECE Recommendation 33, and is closer to concepts behind blockchain technology. UN/CEFACT has produced Reference Data Models that support this approach.

Finally, as has been made clear by now, technical standards are a key part of paperless trade. However, it is important to keep in mind the individual agendas of organizations that push their standards, or that disparage another standard. Many IT companies will make a living off complicated data exchange so it may not be in their interest to have an interoperable system. This is sometimes the case for certain governments or government administrations as well. Nevertheless, as more and more trade and international business processes move online, ensuring interoperability and interconnectivity between systems would help to maximize the benefits of the digital economy. This is as much a strategic regulatory choice as it is a business case.
== Options for Further Trade Governance
Several WTO Members have raised the possibility of discussing paperless trade at the WTO, in some instances in connection with implementing the TFA. This includes suggestions for WTO members to accept electronic trade administration documents and grant these the same legal status as paper versions; and facilitating access to, use of and data exchange with the single window of a member’s authorities for international trade by cross-border e-commerce transaction platforms and traders.

One question raised by the examination above is whether WTO members would be willing to accept any treaty language that takes the form of binding, rather than soft, commitments. To date, most RTAs have not used such language – with a few exceptions in the Asia-Pacific region – except on cooperation and information exchange provisions. What type of principles or cooperative approach could the WTO take? What could be learned from the TFA in terms of graduated levels of commitment and binding?

Certainly, activity is happening outside the WTO, as evidenced by UNECE’s 50-year commitment on the topic. As well as growing prevalence in FTAs, regional initiatives to promote interoperable paperless trading systems are also proceeding, including the UNESCAP paperless trade governance framework. As another example, the Asian Pacific Economic Cooperation (APEC) economies’ 1998 Blueprint for Action on Electronic Commerce included a pledge on reducing the requirement for paper documents for customs or other cross-border trade administration by 2005 for developed economies and by 2010 for developing economies, or as soon as possible thereafter. APEC ministers have recognized the potential of paperless trading on several occasions since and have voluntarily outlined individual action plans on paperless trading from 2002 onward.footnote:[https://www.apec.org/Meeting-Papers/Leaders-Declarations/1998/1998_aelm/apec_blueprint_for.aspx (link as of 09/2017)]

Some countries are also exploring innovative bilateral projects to address new trends. For example, Australia and New Zealand are putting in place an e-commerce “green lane” trial to allow for more seamless movement of low-risk goods through the international mail stream between the two countries. The move is driven by recognition of the increasing volume of low-value e-commerce items in the mail stream. The aim is to pre-screen and pre-clear e-commerce goods using data, enabling faster border clearance, improving efficiency of processes, and directing organizational resources towards high-risk goods. The trial is consistent with a WCO-UPU global model for data exchange between customs and posts, agreed in 2012. The trial will use the WCO-UPU Data Model message formats to support the implementation of Electronic Advance Data (EAD) between post and customs, enabled by the UPU CDS.POST IT platform. To ensure the quality of data, e- traders will be encouraged to provide item-level data electronically.

In light of the above, trade officials, customs authorities, regulators and non- governmental stakeholders wishing to advance paperless trade could consider the following questions to establish intervention points:

* To what extent do your regulatory authorities and other officials already accept electronic submissions of trade-related documents? Is this possible, for example, for certificates of origin, SPS certificates, etc., or only for standard trade documentation?
* Do you treat electronic versions of trade documentation as equivalent to the paper version? If not, why not? What are the areas where paper documentation is still required?
* To what extent does your government already permit electronic payment of duties, taxes and other charges associated with import or export?
* Are your systems aligned with international standards? Which standards? Where are they not aligned? What is the rationale given for why not?
* If paperless systems do not exist currently, what are the limitations preventing their implementation? Are there any near-term plans to build out more paperless trading systems?
* How costly will it be to move towards electronic systems for trade documentation? What types of cost savings might you recoup over time? Is it likely that you will be able to procure the funds to do so?
* Besides cost, what political roadblocks might be encountered in transitioning away from paper for trade documentation and records?
* Are there regional initiatives already under way or ones that could develop in the near future?
* Which business constituencies will be most affected by the switch to paperless systems?
* What types of capacity building programmes will be required to maximize the benefits of paperless trading for SMEs? Is the government equipped to provide this capacity building, or is there another actor that can do so?

Capacity building programmes are a key element to ensure that the benefits of paperless trade are widely available and taken advantage of. Thailand’s Electronic Transactions Development Agency (ETDA) and Office for SME Promotion (OSMEP), for example, have developed a training programme for SMEs to use the national and ASEAN Single Window. An ASEAN Connectivity through Trade and Investment (ACTI) project also hosts working group meetings to boost SME knowledge on the ASW and cargo clearance challenges and expectations. The Republic of Korea’s uTradeHub helps to facilitate a full range of international trade processes from certification and licensing, to customs, logistics and cross-border transaction. SMEs can use the system to conduct negotiations with potential buyers and sellers, address logistics, customs procedures and e- payments.footnote:[http://www.intracen.org/uploadedFiles/intracenorg/Content/Publications/makingwto.pdf (link as of 09/2017)]

Experts also recommend using workshops and consultations with SMEs to discuss the digitalization of trade processes – including taking stock of what trade information is already processed electronically; what blockages exist to SMEs participating in the electronic exchange of documents; and what human resource capacity building and/or other facilities would be needed to enable SMEs to benefit from electronic procedures, such as mobile applications.footnote:[http://www.intracen.org/uploadedFiles/intracenorg/Content/Publications/makingwto.pdf (link as of 09/2017)]

An outstanding question across the policy, technical and business community lies in the application and spread of new advanced technologies. Are businesses in developing countries equipped with the infrastructure and enabling environment to stay connected to international production networks? Will these technologies add costs or make processes easier and cheaper? If applied in a B2G context, how to ensure interoperability and capacity building? International production networks dependent on advances in technology have helped to drive global growth over the past several decades. A world with increased connectivity, digitization and smart technology could accelerate this still further, providing the right frameworks are in place.
 
[[annex-a]]
[appendix]
== Selection of UN/CEFACT Technical Standards

UN/EDIFACT messages cover all aspects of the international supply chain. For example, in the transport sector, UN/EDIFACT covers both contractual messages such as forwarding and consolidation (IFCSUM), booking (IFTMBF), consignment advice (IFTMCA), multimodal status report (IFTSTA), and operational messages such as bay plan/stowage plan (BAPLIE), vessel call (CALINF), and container gate-in/gate-out (CODECO). These messages allow traders to book transport, receive updates on the status of their delivery, declare where containers are on a ship, declare when a ship is to call at a port, communicate when a container arrives or leaves a customs-controlled area, just to give some examples.

Customs messages in UN/EDIFACT are well known around the world by their six- digit abbreviations CUSCAR (cargo reports), CUSDEC (customs declarations), CUSREP (customs response), PAXLST (passenger list) and, more recently, GOVCBR (government cross-border regulatory message). These messages are developed by the World Customs Organization but standardized and maintained by UN/CEFACT.

The supply chain sector also widely uses UN/EDIFACT messages for information such as purchase orders (ORDERS), despatch advices (DESADV), sales forecasts (SLSFCT), and inventory reports (INVRPT). Financial services use a good number of UN/EDIFACT messages such as invoice (INVOIC), remittance advice (REMADV), and quotations (QUOTES). There are also UN/EDIFACT messages in accounting and audit, architecture and construction (in particular for project management), health and insurance, statistics, social security, employment, education and travel/tourism. Being standardized internationally, these all can be used at both cross-border level and national level.

XML is a longer form of data message and so requires more storage space as well as bandwidth for transmission. The segments in XML can have human readable names (known as “tags”) instead of being limited to three characters and the format of the data is less rigid since it is largely disassociated from the paper format. The UN/CEFACT approach to XML focuses on the semantics (data definitions and content) instead of just the outline of the messages themselves. Each UN/CEFACT XML deliverable includes: a Business Requirement Specification (BRS) describing the choreography of events within a process; a Requirements Specification Mapping (RSM) defining the data requirements and all relevant entries in the UN/CEFACT Core Component Library (an encyclopaedia of all data elements); and a resulting XML message (or a series of XML messages, as the case may be).

UN/CEFACT also has three main types of code lists. The first are recommendation code lists which are published as trade-facilitation recommendations (typically the main recommendation describes the code list and its use, and the actual code list is in an annex to facilitate its updating). These cover codes such as packaging, units of measurement, modes of transport and identification of ships, among others. UN/LOCODE is also a recommendation code list and aims to identify all locations linked to international trade; it is essential for the clear identification of locations in the maritime and other transport industries as well as customs. The second are code lists that are maintained within UN/EDIFACT; there are many more of these including, among others, types of documents, types of contracts, types of dates, party function and business function. These two types of code lists are essential in electronic messaging.

The final type is jointly published. These are often recommendation code lists, such as country and currency (jointly published by UN/CEFACT and ISO) and INCOTERMS (jointly published by UN/CEFACT and the International Chamber of Commerce). In all three cases, UN/CEFACT sees its work on codes as important in order to allow the free use of essential lists, as UN/CEFACT publishes all of its code lists free of charge, which is not the case for many other organizations.

[[annex-b]]
[appendix]
== Case Studies of Paperless Trade Implementation
=== e-SPS: Netherlands and China.
International trade in agricultural products is an important economic activity. Many agri-food products require sanitary or phytosanitary (SPS) government certificates to clear customs. These SPS certificates serve as an official communication from the competent authority of the exporting country to the competent authority of the importing country that the cargo meets minimum sanitary requirements. Paper certificates can be costly, are logistically complicated and difficult to protect against fraud. Electronic certificates are also much more accurate than paper certificates. Electronic certificates will lower the number of interceptions and reduce time in ports. Countries are increasingly shifting to electronic customs and port clearance systems to enable better risk management. As a result, relevant regulatory bodies – including IPPC, OIE and CODEX – have recognized electronic certification as an alternative to paper certificates.

The Netherlands and China launched a five-year project in 2010 to pilot the practical implementation of electronic SPS certificates. The project used a step-wise, confidence- building approach, with the two parties initially exchanging information on standards and technology, then subsequently using certificates both in electronic and paper form, and finally moving to a fully digitized system.

The project used a UN/CEFACT standard XML message developed for electronic SPS certificates. Questions arose, however, around ensuring the authenticity of the document. Paper certificates are in most cases produced on security paper and signed and stamped to provide a proof of integrity and authentication. As a result, each electronic message containing the SPS certificate was accompanied by an electronic signature using the XMLDSig standard of the W3C. The management of the electronic signature was based on the FIPS 140-2 (National Institute of Standards and Technology of the USA) standard terms of technology and procedures. The shift also required legal frameworks that recognized the electronic signature.
=== Paperless Air Cargo (IATA Cargo-XML): Jamaica
The International Air Transport Association (IATA) has developed the Cargo-XML Messaging standards using the UN/CEFACT core component library. These Cargo-XML messaging standards are used by the airlines for end-to-end cargo business, fulfil customs’ advance cargo information (ACI) and filing requirements and provide compliance with regulators’ security requirements. The use of core components from the UN/CEFACT data library (CCL) makes the IATA Cargo-XML standards multi-modal and compatible for cross-border movements allowing interoperability between various systems and stakeholders. For example, the IATA Cargo-XML standard is compatible with the WCO Data Model, since both are based on UN/CEFACT core components.

The United Nations Conference on Trade and Development (UNCTAD) has fully integrated IATA Cargo-XML standards into its automated customs management system ASYCUDA World that is used by about 90 countries for their customs procedures. The new data standard improves data quality and simplifies communications across the supply chain facilitating trade growth, helping with cargo security, modernizing customs operations and fostering participation in global commerce through advance electronic data submission for air cargo shipments. It also facilitates customs risk assessments for air cargo shipments and improves compliance with security regulations.

Jamaica was the first country to implement IATA Cargo-XML standards using the UNCTAD ASYCUDA World system for its advance cargo information filing. Carriers flying into Jamaica are required to provide advance information for air waybill, house waybill and flight manifest to Jamaica customs prior to flight arrival using respective IATA Cargo-XML standards. The project is helping to set a foundation for paperless trade; modernizing customs operations; driving better trade efficiency and competitiveness; enhancing security; boosting compliance by carriers with regulatory requirements; and reducing paper waste. Together, these benefits help to lower trade costs, with savings passed on to business and consumers.

The rollout of the IATA Cargo-XML standards in Jamaica was based on several key steps. This included strategic alignment between Jamaican customs, UNCTAD and IATA through regular dialogue to develop a business and IT strategy. The dialogue resulted in the recognition of the WCO SAFE Framework (standards to secure and facilitate global trade) and IATA standard messages, legislative amendments and a roadmap for implementation. There was also a need for resource and implementation planning. Customs and IATA agreed on the implementation approach, as well as filing schedule, amendment and cancellation rules. Customs obtained the necessary documentation (e.g. IATA Cargo-XML Toolkit) and related IATA support. The overall solution initially ran as a pilot. IATA engaged relevant stakeholders to start filing data. UNCTAD and Jamaican customs fine- tuned the solution in accordance with the pilot findings. Jamaican customs, UNCTAD and IATA also developed user guidance and industry communication material such as the filing standards, timelines, responsible parties and compliance conditions, including final enforcement date. IATA is now pursuing a similar approach with other countries for ACI implementation.

=== e-Invoicing for Public Administration: Italy
Starting in June 2014, e-invoicing became mandatory in Italy for public administration bodies, including ministries, tax agencies and national social security – an obligation extended in 2015 to all other government bodies. The Italian banking system consequently developed a model that enables the transmission and issuing of e-invoices. Currently, e-invoice standards in use are proprietary, as defined by the Italian government by specific tags. In the near future, however, the government will be obliged to also support international standards, among which is the UN/CEFACT cross-industry invoice format that has been included in the official EU directive list.

=== Data Pipelines and Reference Data Models: EU
Some EU projects have been working on the concept of “data pipelines”, led by UK and Dutch customs. A data pipeline aims to capture data at its source and manage information along the supply chain, with each actor adding just the information pertinent to their operations.

Several UK IT software providers have adopted this approach to offer added services to their clients. The pipeline, which was originally meant to provide more accuracy in the data sent to government authorities, is also being used to improve supply- chain transparency. Large retail companies execute hundreds of orders and receive many goods containers daily. Until now, opening a container was much like opening a present – uncertain of what would be inside. The pipeline approach allows several larger retailers to directly link the goods ordered to the container and have better visibility of when it will arrive. The data captured at source also allows importers to verify shipments before they actually leave the supplier, helping to avoid errors in supply and packing.

Shipping lines also benefit from the data-pipeline approach. Information can be lost between the steps of traditional paper-driven processes. This may affect the bay plan, such as temperature requirements or actual weights. Putting a heavy container on the upper decks of a ship may cause it to capsize and putting goods that require special attention because of temperature on lower decks may cause these to catch fire and cause disasters. The pipeline approach has already enabled several cases to be identified and avoided.

Data pipelines are largely process-driven. UN/CEFACT has developed a pipeline standard based on the experience of these EU projects. In parallel, the UN/CEFACT Core Component Library (CCL) – an encyclopaedia of all data required for international transactions – has been organized into Reference Data Models that provide only information relevant to a specific area of activity such as logistics or supply chains. As the entire CCL contains information pertinent to all cross-border activity, such as logistics, finance, agriculture, tourism and so on, finding information for a single domain can be difficult with the added information from others. These Reference Data Models, combined with the pipeline approach, enable an event-driven process, communicating snippets of information instead of entire documents. An event-driven process is essential for full Single Window implementation or the eventual application of blockchain technologies to paperless trade.

=== UN/LOCODE: China
As underlined in this paper, the use of internationally recognized code lists is essential for mutual understanding of the data that is being exchanged. One such example is UN/LOCODE.

UN/LOCODE – initially short for the United Nations Code for Ports and other Locations, and later renamed the United Nations Code for Trade and Transport Locations – is specified in UNECE Recommendation 16 as a five-character code to identify locations in a unique and unambiguous way. It provides a coded representation for the names of ports, airports, inland clearance depots, inland freight terminals, and other transport-related locations and trade-related locations that are used for the movement of goods.

UN/LOCODE is used extensively throughout the world by the international trade community. Since a first release in 1981, entries have increased from 8,000 to over 100,000 today, including locations in 249 countries, territories and special areas. It is mandatory to use UN/LOCODE for customs declarations and clearance in many countries. Some examples of standards and organizations that have adopted the use of UN/LOCODE are EDIFACT, the Convention on International Trade in Endangered Species of Wild Flora and Fauna (CITES), the International Maritime Organization, and the WCO.

Since being adopted as a Chinese national standard (GB/T/15514) and obligatory for certain regulatory documents in China, UN/LOCODE has played an important role in facilitating international trade. For example, before Ruago port – a city in Jiangsu province on the eastern coast of China – was assigned with UN/LOCODE, exporters could only deliver goods to Shanghai to then be transported the rest of the journey by highway. For one importer of stone materials, this cost of about around 4,000 renminbi per container – acting as a significant cost draft. After a UN/LOCODE was assigned to Ruago port in 2014, the importer saved about 1.2 billion renminbi annually as the containers are delivered directly.

=== Electronic Single Window: Canada
In 2011 the Canadian Prime Minister Stephen Harper and US President Barack Obama announced a new initiative – Beyond the Border: A Shared Vision for Perimeter Security and Economic Competitiveness – pledging to develop common border practices, and streamlining customs processing and regulatory compliance. A joint action plan identified full implementation of an electronic single window as one of 32 joint priorities. Both Canada and the US were to convert to electronic form data requirements of all government departments and agencies participating in the initiative by 2013, as well as for border-related decision processes for at least the top four priority departments.

As the lead agency, the Canada Border Services Agency (CBSA) developed its Single Window in accordance with the UN/CEFACT Recommendation 33 (on establishing a Single Window); Recommendation 34 (on trade data simplification and standardization); and Recommendation 36 (on Single Window interoperability). CBSA also ensured that representatives from all relevant public and private sector agencies were involved from initiation through to implementation. Oversight, review and contribution were also made by stakeholders, including participating government departments and agencies (PGA), trade chain partners (importers, carriers, brokers and freight-forwarders) and international partnerships (UN/CEFACT, US Customs and Border Protection, the WTO, the WCO, and APEC).

The CBSA began with specific PGA needs assessments to assess the challenges associated with the cross-border movement of commercial goods. Input from policy experts helped to verify data definitions and established the necessity of the information to fulfil the mandate of the particular PGA and its associated programme(s) – resulting in the reduction of 1,800 required data elements to 80. The CBSA also worked with the PGAs to ensure that the proper legal authorities were in place to collect, share and store the data.

The CBSA chose to develop a Single Automated System (a single, centrally maintained submission system with which all authorities and traders have to interface) in accordance with industry Project Management Lifecycle principles and standards, designed to streamline the electronic collection and dissemination of commercial import data between the Government of Canada and the import community. Its creation established a solution for the commercial import process that balances the needs of government departments and agencies with today’s globally competitive business environment through the development of the Integrated Import Declaration (IID) and the Document Imaging Functionality (DIF).

Three Risk Assessment Information Sharing Models were developed and could be customized to suit the needs of the specific PGAs and their programme:

* Model 1: PGAs review the IID data and provide an active recommendation to the CBSA
* Model 2: PGAs do not provide an active recommendation to the CBSA –instead the information on the IID is validated electronically by the PGA; and the CBSA maintains a list of PGA rules via a Business Management Rules System
* Model 3: Enhanced Pathfinder Delivery – provides participants with commercial trade data, currently collected by the CBSA, through the use of data extract files

With more timely, complete and accurate information provided by importers and
brokers via the Single Window, the CBSA is in a better position to make release decisions. Automated functions such as business rule validation and the use of the DIF allows the agency to efficiently allocate border service officers. The PGAs, in turn, are able to perform more effective risk assessments when making recommendations to the CBSA. Additionally, PGAs are able to participate in real-time admissibility determinations along with the CBSA because of the advanced trade data and other technical means.

As of March 2017 10 PGAs and their 38 associated programmes were using the IID. Canada continues to ensure interoperability through continued collaboration with US customs. Efforts are also made to continue work with relevant business as well as ensuring ongoing alignment with international recommendations and standards through continued partnership with UN/CEFACT and in the ongoing development and implementation of the WCO Data Model.



